name: fitzai
channels:
  - defaults
dependencies:
  - python=3.11
  - python-dotenv=1.1.0
  - psycopg2=2.9.10
  - notebook
  - pandas
  - openpyxl=3.1.5
  - sqlalchemy
  - openai
  - tabulate=0.9.0
  - anaconda::scikit-learn
  - ipywidgets==8.1.5
  - transformers==4.51.3
  - langchain==0.3.25
  - pip
  - pip:
      - tensorflow[and-cuda]
      - tf-keras
      - torch
      - torchvision
      - torchaudio
      - chromadb
      - sentence-transformers
      - langchain-chroma==0.2.4
      - langchain-huggingface==0.3.0
      - langchain-openai==0.3.28
